[workspace]
members = [
    "test-manager",
    "test-runner",
]

[patch.crates-io]
serialport = { git = "https://github.com/Mullvad/serialport-rs", rev = "1401c9d39e4a89685e3506a7160869b2c8e9ceb0" }
