[lib]
proc-macro = true

[package]
name = "test_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
convert_case = "0.6"

test-rpc = { path = "../../test-rpc" }
